// SVGs
export { default as logo } from './logo.png'
export { default as AccountIcon } from './svg/account.svg'
export { default as CartIcon } from './svg/cart.svg'
export { default as CrossIcon } from './svg/cross.svg'
export { default as GarbageIcon } from './svg/garbage.svg'
export { default as LeftArrowIcon } from './svg/left-arrow.svg'
export { default as MenuIcon } from './svg/menu.svg'
export { default as LaptopIcon } from './svg/products/laptop.svg'
export { default as SmartphoneIcon } from './svg/products/smartphone.svg'
export { default as RightArrowIcon } from './svg/right-arrow.svg'
export { default as SearchIcon } from './svg/search.svg'
export { default as StarIcon } from './svg/star.svg'
export { default as WishlistIcon } from './svg/wishlist.svg'
export { default as TestProduct } from './test-product.png'
