export { default as Footer } from './layout/footer/Footer'
export { default as Header } from './layout/header/Header'
export { default as Button } from './ui/button/Button'
export { default as ProductsList } from './ui/products/ProductsList'
export { default as SearchBar } from './ui/searchbar/SearchBar'
