//* SVGs
export { default as AccountIcon } from './svgs/account.svg'
export { default as AccountCardIcon } from './svgs/account-card.svg'
export { default as ArchiveIcon } from './svgs/archive.svg'
export { default as CartIcon } from './svgs/cart.svg'
export { default as CrossIcon } from './svgs/cross.svg'
export { default as DiagonalArrowLeftIcon } from './svgs/diagonal-arrow-left.svg'
export { default as EllipsisIcon } from './svgs/ellipsis.svg'
export { default as FacebookIcon } from './svgs/facebook.svg'
export { default as GarbageIcon } from './svgs/garbage.svg'
export { default as GoogleIcon } from './svgs/google.svg'
export { default as HeadphonesIcon } from './svgs/headphones.svg'
export { default as LaptopIcon } from './svgs/laptop.svg'
export { default as LeftArrowIcon } from './svgs/left-arrow.svg'
export { default as LogoutIcon } from './svgs/logout.svg'
export { default as MenuIcon } from './svgs/menu.svg'
export { default as PaymentIcon } from './svgs/payment.svg'
export { default as RightArrowIcon } from './svgs/right-arrow.svg'
export { default as SearchIcon } from './svgs/search.svg'
export { default as ShowPasswordIcon } from './svgs/show-password.svg'
export { default as SignInIcon } from './svgs/sign-in.svg'
export { default as SmartphoneIcon } from './svgs/smartphone.svg'
export { default as StarIcon } from './svgs/star.svg'
export { default as TelegramIcon } from './svgs/telegram.svg'
export { default as WatchIcon } from './svgs/watch.svg'
export { default as WishlistIcon } from './svgs/wishlist.svg'

//* IMG
export { default as DefaultAvatar } from './images/default-user-avatar.png'
export { default as Logo } from './images/logo.png'
export { default as NoProductsPng } from './images/NoProducts.png'
export { default as NoWishlistProductsWebp } from './images/NoWishlist.webp'
export { default as SuccessOrder } from './images/success-order.png'
export { default as TestProduct } from './images/test-product.png'
